import {createClient} from 'npm:@supabase/supabase-js@2.57.4';
import Stripe from 'npm:stripe@18.5.0';
export const env=(key:string)=>{const v=Deno.env.get(key);if(!v)throw new Error(`Missing ${key}`);return v;};
const adminKey=()=>Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || JSON.parse(env('SUPABASE_SECRET_KEYS')).default;
export const admin=()=>createClient(env('SUPABASE_URL'),adminKey(),{auth:{persistSession:false,autoRefreshToken:false}});
export const stripe=()=>new Stripe(env('STRIPE_SECRET_KEY'),{httpClient:Stripe.createFetchHttpClient()});
export const site=()=>env('SITE_URL').replace(/\/$/,'');
export function headers(req:Request){const origin=req.headers.get('origin')||'';const allowed=origin===new URL(site()).origin;return {'Access-Control-Allow-Origin':allowed?origin:'null','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin','Content-Type':'application/json'};}
export function json(req:Request,value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:headers(req)});}
export class PublicError extends Error{constructor(message:string,public status=400){super(message);}}
export function endpoint(handler:(req:Request)=>Promise<Response>){Deno.serve(async req=>{try{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='POST')return json(req,{error:'Método não permitido.'},405);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(site()).origin)return json(req,{error:'Origem não permitida.'},403);return await handler(req);}catch(e){console.error('Request failed',e instanceof PublicError?e.message:'internal error');return json(req,{error:e instanceof PublicError?e.message:'Serviço temporariamente indisponível. Tente novamente.'},e instanceof PublicError?e.status:500);}});}
export async function authenticate(req:Request){const token=req.headers.get('authorization')?.match(/^Bearer (.+)$/i)?.[1];if(!token)throw new PublicError('Entre na sua conta.',401);const db=admin();const {data,error}=await db.auth.getUser(token);if(error||!data.user)throw new PublicError('Sessão expirada. Entre novamente.',401);return {db,user:data.user};}
export async function boundedJSON(req:Request,max:number){if(Number(req.headers.get('content-length'))>max)throw new PublicError('Arquivo muito grande.',413);const reader=req.body?.getReader();if(!reader)throw new PublicError('Requisição vazia.');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new PublicError('Arquivo muito grande.',413);}chunks.push(value);}const data=new Uint8Array(size);let offset=0;for(const chunk of chunks){data.set(chunk,offset);offset+=chunk.length;}try{return JSON.parse(new TextDecoder().decode(data));}catch{throw new PublicError('Dados inválidos.');}}
