// Run with Node 24+. No external dependency and no real API calls.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {stripTypeScriptTypes}=require('node:module');
class PublicError extends Error{constructor(message,status=400){super(message);this.status=status;}}
function load(name,overrides={}){let handler;const context={console,Request,Response,AbortSignal,atob,Date,JSON,PublicError,endpoint:f=>handler=f,json:(_,value)=>value,env:k=>({STRIPE_PRICE_ID:'price_valid',OPENAI_API_KEY:'test',SITE_URL:'https://example.com'}[k]||'test'),site:()=> 'https://example.com',authenticate:async()=>{throw new PublicError('Unauthorized',401);},boundedJSON:async r=>r.json(),stripe:()=>({}),Deno:{env:{get:()=>undefined},serve:f=>handler=f},...overrides};let code=fs.readFileSync(path.join(__dirname,'../supabase/functions',name,'index.ts'),'utf8').replace(/^import .*;\n/gm,'');code=stripTypeScriptTypes(code,{mode:'transform'});vm.runInNewContext(code,context);return (...args)=>handler(...args);}
const req=body=>new Request('https://example.com',{method:'POST',body:JSON.stringify(body)});
const image='data:image/jpeg;base64,'+Buffer.from([255,216,255,224,0,0]).toString('base64');
test('analyze requires authentication',async()=>{const fn=load('analyze');await assert.rejects(()=>fn(req({image,context:''})),e=>e.status===401);});
test('invalid file rejected before quota or AI',async()=>{let touched=false;const fn=load('analyze',{authenticate:async()=>({user:{id:'u'},db:{rpc:()=>{touched=true;}}})});await assert.rejects(()=>fn(req({image:'data:image/jpeg;base64,aGVsbG8=',context:''})),/JPG/);assert.equal(touched,false);});
test('quota refusal stops AI',async()=>{const fn=load('analyze',{authenticate:async()=>({user:{id:'u'},db:{rpc:async()=>({error:{message:'QUOTA_EXCEEDED'}})}}),fetch:()=>{throw Error('must not call');}});await assert.rejects(()=>fn(req({image,context:''})),e=>e.status===429);});
test('provider failure refunds reserved quota',async()=>{const calls=[];const fn=load('analyze',{authenticate:async()=>({user:{id:'u'},db:{rpc:async(name)=>{calls.push(name);return {data:'2026-10-01',error:null};}}}),fetch:async()=>({ok:false})});await assert.rejects(()=>fn(req({image,context:''})),/AI unavailable/);assert.deepEqual(calls,['reserve_analysis','refund_analysis']);});
test('successful analysis saves real structured result',async()=>{const result={plant:'Teste',confidence:'baixa',summary:'inconclusivo',observations:[],care:[],possible_causes:[],next_steps:[],treatment:[],caution:'teste'};let saved;const db={rpc:async()=>({data:'2026-10-01'}),from:()=>({insert:v=>{saved=v;return {select:()=>({single:async()=>({data:{id:'a'}})})};}})};const fn=load('analyze',{authenticate:async()=>({user:{id:'u'},db}),fetch:async()=>({ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(result)}]}]})})});const out=await fn(req({image,context:''}));assert.equal(out.id,'a');assert.equal(saved.user_id,'u');assert.equal(saved.result.plant,'Teste');});
test('checkout sends existing subscriber to portal',async()=>{const db={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{stripe_customer_id:'cus_a'}})})})})};const fn=load('checkout',{authenticate:async()=>({user:{id:'u',email_confirmed_at:'date'},db}),stripe:()=>({subscriptions:{list:async()=>({data:[{status:'active'}]})},billingPortal:{sessions:{create:async()=>({url:'https://billing.stripe.com/mock'})}}})});assert.equal((await fn(req({}))).url,'https://billing.stripe.com/mock');});
test('checkout rejects wrong amount configured on Stripe',async()=>{const db={from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{stripe_customer_id:'cus_a'}})})})})};const fn=load('checkout',{authenticate:async()=>({user:{id:'u',email_confirmed_at:'date'},db}),stripe:()=>({subscriptions:{list:async()=>({data:[]})},prices:{retrieve:async()=>({active:true,currency:'brl',unit_amount:4900,recurring:{interval:'month',interval_count:1}})}})});await assert.rejects(()=>fn(req({})),/BRL 4700/);});
test('webhook rejects absent signature',async()=>{const fn=load('stripe-webhook',{Stripe:{createSubtleCryptoProvider:()=>({})}});assert.equal((await fn(req({}))).status,400);});
test('webhook rejects invalid signature',async()=>{const fn=load('stripe-webhook',{Stripe:{createSubtleCryptoProvider:()=>({})},stripe:()=>({webhooks:{constructEventAsync:async()=>{throw Error('bad signature');}}})});const r=new Request('https://example.com',{method:'POST',headers:{'stripe-signature':'invalid'},body:'{}'});assert.equal((await fn(r)).status,400);});
